# You should rename this file to config.yml for use
# This section are describes possible targets to connections
target:
  database:
    db_name: "db name"
    db_host: "ip address"
    db_user: "db username"
    db_password: "db password"
